PRODUCTS = [
    {'name': 'Baby Yoda Blueball', 'description': 'Figura coleccionable de Baby Yoda (Grogu) - The Mandalorian Saga, edición limitada.', 'price': 1799.99, 'stock': 8, 'discount': 5.00, 'sku': 'STW001001', 'dues': 3, 'special': 0, 'image_front': 'images/Star-Wars/funkos/Baby-Yoda-Blueball_front.webp', 'image_back': 'images/Star-Wars/funkos/Baby-Yoda-Blueball_back.webp', 'licence_id': 2, 'category_id': 1},
    {'name': 'Luke Skylwalker & Grogu', 'description': 'Figura coleccionable de Luke Skylwalker & Grogu - The Mandalorian Saga.', 'price': 2399.99, 'stock': 8, 'discount': 15.00, 'sku': 'STW001003', 'dues': 3, 'special': 0, 'image_front': 'images/Star-Wars/funkos/Luke_Skylwalker_&_Grogu_front.webp', 'image_back': 'images/Star-Wars/funkos/Luke_Skylwalker_&_Grogu_back.webp', 'licence_id': 2, 'category_id': 1},
    {'name': 'Stormtrooper Lightsaber', 'description': 'Figura coleccionable de Stormtrooper Lightsaber - Star Wars Saga.', 'price': 1799.99, 'stock': 8, 'discount': 20.00, 'sku': 'STW001004', 'dues': 3, 'special': 0, 'image_front': 'images/Star-Wars/funkos/Stormtrooper_Lightsaber_front.webp', 'image_back': 'images/Star-Wars/funkos/Stormtrooper_Lightsaber_back.webp', 'licence_id': 2, 'category_id': 1},
    {'name': 'Charmander Smiley', 'description': 'Figura coleccionable de Charmander - Pokemon Saga.', 'price': 1799.99, 'stock': 8, 'discount': 10.00, 'sku': 'PKM001001', 'dues': 3, 'special': 0, 'image_front': 'images/Pokemon/funkos/Charmander_Smiley_front.webp', 'image_back': 'images/Pokemon/funkos/Charmander_Smiley_back.webp', 'licence_id': 1, 'category_id': 1},
    {'name': 'Dragonite Hi!', 'description': 'Figura coleccionable de Dragonite - Pokemon Saga.', 'price': 1799.99, 'stock': 8, 'discount': 10.00, 'sku': 'PKM001002', 'dues': 3, 'special': 0, 'image_front': 'images/Pokemon/funkos/Dragonite_Hi!_front.webp', 'image_back': 'images/Pokemon/funkos/Dragonite_Hi!_back.webp', 'licence_id': 1, 'category_id': 1},
    {'name': 'Pidgeotto Flying', 'description': 'Figura coleccionable de Pidgeotto - Pokemon Saga.', 'price': 1799.99, 'stock': 8, 'discount': 30.00, 'sku': 'PKM00103', 'dues': 3, 'special': 1, 'image_front': 'images/Pokemon/funkos/Pidgeotto_Flying_front.webp', 'image_back': 'images/Pokemon/funkos/Pidgeotto_Flying_back.webp', 'licence_id': 1, 'category_id': 1},
    {'name': 'Pikachu Smiley', 'description': 'Figura coleccionable de Pikachu - Pokemon Saga.', 'price': 1799.99, 'stock': 8, 'discount': 10.00, 'sku': 'PKM001004', 'dues': 3, 'special': 0, 'image_front': 'images/Pokemon/funkos/Pikachu_Smiley_front.webp', 'image_back': 'images/Pokemon/funkos/Pikachu_Smiley_back.webp', 'licence_id': 1, 'category_id': 1},
    {'name': 'Vulpix Fancy', 'description': 'Figura coleccionable de Vulpix - Pokemon Saga.', 'price': 99.99, 'stock': 8, 'discount': 10.00, 'sku': 'PKM001005', 'dues': 3, 'special': 0, 'image_front': 'images/Pokemon/funkos/Vulpix_Fancy_front.webp', 'image_back': 'images/Pokemon/funkos/Vulpix_Fancy_back.webp', 'licence_id': 1, 'category_id': 1},
    {'name': 'Harry Potter & Hegwid', 'description': 'Figura coleccionable de Harry Potter & Hegwid - Harry Potter Saga.', 'price': 1799.99, 'stock': 11, 'discount': 10.00, 'sku': 'HPT001001', 'dues': 9, 'special': 0, 'image_front': 'images/Harry-Potter/funkos/Harry_Potter_&_Hegwid_front.webp', 'image_back': 'images/Harry-Potter/funkos/Harry_Potter_&_Hegwid_back.webp', 'licence_id': 3, 'category_id': 1},
    {'name': 'Kakashi Hatake Shippuden', 'description': 'Kakashi Hatake Shippuden', 'price': 1999.99, 'stock': 20, 'discount': 10.00, 'sku': 'NRT001001', 'dues': 9, 'special': 0, 'image_front': 'images/Naruto/funkos/Kakashi_Hatake_Shippuden_front.webp', 'image_back': 'images/Naruto/funkos/Kakashi_Hatake_Shippuden_back.webp', 'licence_id': 4, 'category_id': 1},
    {'name': 'Harry Potter', 'description': 'Remera coleccionable de Harry Potter.', 'price': 100.00, 'stock': 999, 'discount': 10.00, 'sku': 'HPT003001', 'dues': 6, 'special': 1, 'image_front': 'images/Harry-Potter/remeras/Harry_Potter_front.webp', 'image_back': 'images/Harry-Potter/remeras/Harry_Potter_back.webp', 'licence_id': 3, 'category_id': 2}
]